package events

type EventTyp string

const (
	EventTypeSendVote                          EventTyp = "sendVote"
	EventTypeSendNewRoundStep                  EventTyp = "sendNewRoundStep"
	EventTypeSendNewValidBlock                 EventTyp = "sendNewValidBlock"
	EventTypeSendProposal                      EventTyp = "sendProposal"
	EventTypeSendProposalPOL                   EventTyp = "sendProposalPOL"
	EventTypeSendBlockPart                     EventTyp = "sendBlockPart"
	EventTypeSendHasVote                       EventTyp = "sendHasVote"
	EventTypeSendVoteSetMaj23                  EventTyp = "sendVoteSetMaj23"
	EventTypeSendVoteSetBits                   EventTyp = "sendVoteSetBits"
	EventTypeSendHasProposalBlockPart          EventTyp = "sendHasProposalBlockPart"
	EventTypeReceivePacketNewRoundStep         EventTyp = "receivePacketNewRoundStep"
	EventTypeReceivePacketNewValidBlock        EventTyp = "receivePacketNewValidBlock"
	EventTypeReceivePacketProposal             EventTyp = "receivePacketProposal"
	EventTypeReceivePacketProposalPOL          EventTyp = "receivePacketProposalPOL"
	EventTypeReceivePacketBlockPart            EventTyp = "receivePacketBlockPart"
	EventTypeReceivePacketVote                 EventTyp = "receivePacketVote"
	EventTypeReceivePacketHasVote              EventTyp = "receivePacketHasVote"
	EventTypeReceivePacketVoteSetMaj23         EventTyp = "receivePacketVoteSetMaj23"
	EventTypeReceivePacketVoteSetBits          EventTyp = "receivePacketVoteSetBits"
	EventTypeReceivePacketHasProposalBlockPart EventTyp = "receivePacketHasProposalBlockPart"
	EventTypeReceiveVote                       EventTyp = "receiveVote"
	EventTypeReceivedProposal                  EventTyp = "receivedProposal"
	EventTypeReceivedCompleteProposalBlock     EventTyp = "receivedCompleteProposalBlock"
	EventTypeProposeStep                       EventTyp = "proposeStep"
	EventTypeEnteringPrevoteStep               EventTyp = "enteringPrevoteStep"
	EventTypeEnteringPrecommitStep             EventTyp = "enteringPrecommitStep"
	EventTypeEnteringPrevoteWaitStep           EventTyp = "enteringPrevoteWaitStep"
	EventTypeEnteringPrecommitWaitStep         EventTyp = "enteringPrecommitWaitStep"
	EventTypeEnteringCommitStep                EventTyp = "enteringCommitStep"
	EventTypeEnteringWaitStep                  EventTyp = "enteringWaitStep"
	EventTypeEnteringNewRound                  EventTyp = "enteringNewRound"
	EventTypeScheduledTimeout                  EventTyp = "scheduledTimeout"
	EventTypeP2pVote                           EventTyp = "p2pVote"
	EventTypeP2pBlockPart                      EventTyp = "p2pBlockPart"
	EventTypeP2pProposal                       EventTyp = "p2pProposal"
	EventTypeP2pProposalPOL                    EventTyp = "p2pProposalPOL"
	EventTypeP2pNewRoundStep                   EventTyp = "p2pNewRoundStep"
	EventTypeP2pHasVote                        EventTyp = "p2pHasVote"
	EventTypeP2pVoteSetMaj23                   EventTyp = "p2pVoteSetMaj23"
	EventTypeP2pVoteSetBits                    EventTyp = "p2pVoteSetBits"
	EventTypeP2pHasProposalBlockPart           EventTyp = "p2pHasProposalBlockPart"
)
